linters-settings:
  gocyclo:
    # minimal code complexity to report
    min-complexity: 10
  maligned:
    # print struct with more effective memory layout
    suggest-new: true
  lll:
    line-length: 512
  cyclop:
    # minimal code complexity to report
    max-complexity: 15

linters:
  enable-all: true
  disable:
    - execinquery
    - wrapcheck
    - revive
    - funlen
    - wsl
    - gocyclo
    - errcheck
    - gomnd
    - paralleltest
    - forbidigo
    - mnd
    - depguard
    - gofumpt
    - gochecknoglobals
    - err113

issues:
  exclude-use-default: true
  # Maximum issues count per one linter. Set to 0 to disable.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable
  max-same: 0

  # Show only new issues
  new: false
