name: learn-github-actions
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          check-latest: true
      - run: go install github.com/onsi/ginkgo/v2/ginkgo@latest
      - run: ginkgo --randomize-suites --randomize-all -r
