name: learn-github-actions
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - run: go install github.com/onsi/ginkgo/v2/ginkgo@latest
      - run: ginkgo --randomize-suites --randomize-all -p -r
